// filter categories
const categories = [
    {
      name: 'All',
      filter: 'all',
    },
    {
      name: 'Illustrations',
      filter: 'illustrations',
    },
    {
      name: 'Digital Art',
      filter: 'digital art',
    },
    {
      name: 'Graphic Designing',
      filter: 'graphic designing',
    },
    {
      name: '3D Modelling',
      filter: '3D modelling',
    },
    {
      name: 'Javascript projects',
      filter: 'javascript projects',
    },
  ];
  
  const images = [
    {
      id: '1',
      url: 'img1.jpg',
      category: 'digital art',
      title: 'karina',
    },
    {
      id: '2',
      url: 'img2.jpg',
      category: 'digital art',
      title: 'Aurora',
    },
    {
      id: '3',
      url: 'img3.jpg',
      category: 'animation',
      title: 'Wedding 2',
    },
    {
      id: '4',
      url: 'img4.jpg',
      category: 'graphic designing',
      title: 'Beach and Sea from drone',
    },
    {
      id: '5',
      url: 'img5.jpg',
      category: 'graphic designing',
      title: 'Mountain',
    },
    {
      id: '6',
      url: 'img6.jpg',
      category: 'graphic designing',
      title: 'Road from Drone',
    },
    {
      id: '7',
      url: 'img7.jpg',
      category: 'illustrations',
      title: 'Portrait 1',
    },
    {
      id: '8',
      url: 'img8.jpg',
      category: 'illustrations',
      title: 'Wedding 1',
    },
    {
      id: '9',
      url: 'img9.jpg',
      category: 'graphic designing',
      title: 'Hills',
    },
    {
      id: '10',
      url: 'img10.jpg',
      category: 'illustrations',
      title: 'Portrait 2',
    },
    {
      id: '11',
      url: 'img11.jpg',
      category: 'graphic designing',
      title: 'Lake',
    },
    {
      id: '12',
      url: 'img12.jpg',
      category: 'graphic designing',
      title: 'Landscape lake',
    },
    {
      id: '13',
      url: 'img13.jpg',
      category: 'graphic designing',
      title: 'Mountain Snowy',
    },
    {
      id: '14',
      url: 'img14.jpg',
      category: 'graphic designing',
      title: 'Aurora2',
    },
    {
      id: '15',
      url: 'img15.jpg',
      category: 'graphic designing',
      title: 'Mountain Green',
    },
    {
      id: '16',
      url: 'img16.jpg',
      category: 'digital art',
      title: 'Portrait 3',
    },
    {
      id: '17',
      url: 'img17.jpg',
      category: 'digital art',
      title: 'Portrait 4',
    },
    {
      id: '18',
      url: 'img18.jpg',
      category: 'graphic designing',
      title: 'Portrait 5',
    },
    {
      id: '19',
      url: 'img19.jpg',
      category: 'digital art',
      title: 'Portrait 6',
    },
    {
      id: '20',
      url: 'img20.jpg',
      category: 'digital art',
      title: 'Portrait 7',
    },
    {
      id: '21',
      url: 'img21.jpg',
      category: 'graphic designing',
      title: 'Wedding ',
    },
    {
      id: '22',
      url: 'img22.jpg',
      category: 'graphic designing',
      title: 'Wedding ',
    },
    {
      id: '23',
      url: 'img23.jpg',
      category: 'graphic designing',
      title: 'Wedding ',
    },
    {
      id: '24',
      url: 'img24.jpg',
      category: 'graphic designing',
      title: 'Wedding ',
    },
    {
      id: '25',
      url: 'img25.jpg',
      category: 'graphic designing',
      title: 'Drone 1',
    },
    {
      id: '26',
      url: 'img26.jpg',
      category: 'illustrations',
      title: 'Drone 2',
    },
    {
      id: '27',
      url: 'img27.jpg',
      category: 'illustrations',
      title: 'Drone 3',
    },
    {
      id: '28',
      url: 'img28.jpg',
      category: '3D modelling',
      title: 'VIDEO',
    },
    {
      id: '29',
      url: 'img29.jpg',
      category: 'javascript projects',
      title: 'Drone 5',
    },
    {
      id: '30',
      url: 'img30.jpg',
      category: 'javascript projects',
      title: 'Drone 5',
    },
    {
      id: '31',
      url: 'img31.jpg',
      category: 'javascript projects',
      title: 'Drone 5',
    },
    {
      id: '32',
      url: 'img32.jpg',
      category: '3D modelling',
      title: 'image',
    },
    {
      id: '33',
      url: 'img33.jpg',
      category: '3D modelling',
      title: 'image',
    },
    {
      id: '34',
      url: 'img34.jpg',
      category: '3D modelling',
      title: 'image',
    },
    {
      id: '35',
      url: 'img35.jpg',
      category: '3D modelling',
      title: 'image',
    },
    {
      id: '36',
      url: 'img36.jpg',
      category: '3D modelling',
      title: 'image',
    },
    {
      id: '37',
      url: 'img37.jpg',
      category: '3D modelling',
      title: 'image',
    },
    {
      id: '38',
      url: 'img38.jpg',
      category: '3D modelling',
      title: 'image',
    },
    {
      id: '39',
      url: 'img39.jpg',
      category: '3D modelling',
      title: 'image',
    },
    {
      id: '40',
      url: 'img40.jpg',
      category: '3D modelling',
      title: 'image',
    },
    {
      id: '41',
      url: 'img41.jpg',
      category: '3D modelling',
      title: 'image',
    },
    {
      id: '42',
      url: 'img42.jpg',
      category: '3D modelling',
      title: 'image',
    },
    {
      id: '43',
      url: 'img43.jpg',
      category: '3D modelling',
      title: 'image',
    },
    {
      id: '44',
      url: 'img44.jpg',
      category: '3D modelling',
      title: 'image',
    },
    {
      id: '45',
      url: 'img45.jpg',
      category: '3D modelling',
      title: 'image',
    },
  ];